Feature/reset global
qiwi/pijma-v2 pull request #107
Opened 2022-12-15 14:45 UTC by RodionLeginkov

Fixes [#id]

## Changes

- [ ] New code is covered by tests
- [ ] All the changes are mentioned in docs (readme.md)

2022-12-15 16:30 UTC, oljekechoro requested changes

2022-12-15 16:30 UTC, oljekechoro commented on demo-spa/src/Container/Home/index.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
думаю не стоит на весь файл игнор, надо как можно меньше any

2022-12-15 17:39 UTC, RodionLeginkov commented on demo-spa/src/Container/Home/index.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Поменял и добавил wrapper для компонентов

2022-12-16 09:04 UTC, lpk3nny approved these changes

2022-12-16 09:09 UTC, oljekechoro approved these changes

2022-12-16 09:13 UTC, merged