Add select
qiwi/pijma-v2 pull request #118
Opened 2023-01-18 15:07 UTC by RodionLeginkov

Fixes [#id]

## Changes

- [ ] New code is covered by tests
- [ ] All the changes are mentioned in docs (readme.md)

2023-01-18 16:16 UTC, lpk3nny requested changes

2023-01-18 16:16 UTC, lpk3nny commented on packages/components/select/src/main/mdx/Select.stories.mdx
> +
Нужно вот сюда добавить Story с компонентом без обертки. чтобы можно было тыкать свойства с панели Controls на Canvas view

2023-01-18 16:16 UTC, lpk3nny commented on packages/components/select/src/main/ts/Select.tsx
> +        tabIndex={0}
Можно в пропсы выкинуть. В первой пижме так

2023-01-18 16:16 UTC, lpk3nny commented on packages/components/select/src/main/ts/Select.tsx
> +          <IconB2CAngleDown width={24} height={24} />
В тему

2023-01-18 16:24 UTC, oljekechoro submitted a review, later dismissed

2023-01-19 10:09 UTC, lpk3nny approved these changes

2023-01-19 10:12 UTC, antongolub approved these changes

2023-01-19 10:15 UTC, merged