Feat/tabs
qiwi/pijma-v2 pull request #68
Opened 2022-11-21 10:43 UTC by lpk3nny

tabs draft version

## Changes

- [ ] New code is covered by tests
- [ ] All the changes are mentioned in docs (readme.md)

2022-11-21 13:57 UTC, oljekechoro commented on packages/components/tabs/package.json
> +    "@pijma/theme-b2b": "workspace:*",
а темы разве тут используются?

2022-11-21 13:57 UTC, oljekechoro commented on index.js
> +import {light} from '@pijma/theme'
кажется забыл убрать

2022-11-21 14:01 UTC, oljekechoro requested changes

2022-11-21 14:01 UTC, oljekechoro commented on packages/components/tabs/src/themes/b2b.style.ts
> +// export const B2BTheme = {
тут тоже забыл убрать

2022-11-22 08:21 UTC, oljekechoro requested changes

2022-11-22 08:21 UTC, oljekechoro commented on packages/components/tabs/src/themes/b2b.style.ts
>          TabsWrapper: () => {
А почему бы не объединить обе фабрики?

2022-11-22 08:21 UTC, oljekechoro commented on packages/themes/b2b/src/light/theme.ts
> +    TabHeader: TabHeaderStylesB2BFactory(common),
Мне кажется, в теме не стоит детализироваться до субкомпонентов

2022-11-22 08:26 UTC, lpk3nny commented on packages/themes/b2b/src/light/theme.ts
> +    TabHeader: TabHeaderStylesB2BFactory(common),
потому что они разные типы пропсов жрут. одна для компонента Tabs, другая для конкретного TabHeader. мне это и не нравится. что надо делать под каждый вложенный компонент новую фабрику
или можно так сделать?

2022-11-22 08:26 UTC, lpk3nny commented on packages/components/tabs/src/themes/b2b.style.ts
>          TabsWrapper: () => {
потому что они разные типы пропсов жрут. одна для компонента Tabs, другая для конкретного TabHeader. мне это и не нравится. что надо делать под каждый вложенный компонент новую фабрику
или можно так сделать?

2022-11-22 14:57 UTC, oljekechoro approved these changes

2022-11-22 15:00 UTC, merged