Feat/playwright test
qiwi/pijma-v2 pull request #96
Opened 2022-12-07 08:07 UTC by lpk3nny

Fixes [#id]

## Changes

- [ ] New code is covered by tests
- [ ] All the changes are mentioned in docs (readme.md)

2022-12-09 14:07 UTC, oljekechoro requested changes

2022-12-09 14:07 UTC, oljekechoro commented on packages/components/alert/src/main/ts/themes/b2c.style.ts
> +        // height: '24px',
а это не должно быть раскоменчено или удалено?

2022-12-12 07:59 UTC, lpk3nny commented on packages/components/alert/src/main/ts/themes/b2c.style.ts
> +        // height: '24px',
нет. это сделано чтобы соответствовать дизайну с первой пижмы. там отступ получается больше чем надо по логике, но раз так было, придется так и оставить

2022-12-12 08:54 UTC, oljekechoro approved these changes

2022-12-12 08:54 UTC, merged